"""Generate responsive WebP derivatives; retain original project photography.

Run with Python and Pillow. The generated manifest is loaded before portfolio-data.js.
"""
import hashlib
import json
import re
from pathlib import Path
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
source = (ROOT / 'assets/js/portfolio-data.js').read_text(encoding='utf-8')
paths = sorted(set(re.findall(r"['\"](/public/projects/[^'\"]+\.(?:png|webp|jpg|jpeg))['\"]", source, re.I)))
manifest = {}
original_bytes = 0
gallery_bytes = 0
for url in paths:
    original = ROOT / url.lstrip('/')
    if not original.is_file():
        raise FileNotFoundError(original)
    original_bytes += original.stat().st_size
    digest = hashlib.sha256(original.read_bytes()).hexdigest()[:10]
    destination = ROOT / 'public/projects/optimized' / original.parent.name
    destination.mkdir(parents=True, exist_ok=True)
    with Image.open(original) as opened:
        image = ImageOps.exif_transpose(opened).convert('RGB')
        variants = []
        for width in sorted({min(n, image.width) for n in (240, 640, 960, 1600)}):
            resized = image.resize((width, round(image.height * width / image.width)), Image.Resampling.LANCZOS)
            target = destination / f'{original.stem}-{digest}-{width}.webp'
            if not target.exists():
                resized.save(target, 'WEBP', quality=86, method=6)
            variants.append(('/' + target.relative_to(ROOT).as_posix(), width, resized.height))
        src, width, height = variants[-1]
        gallery_bytes += (ROOT / src.lstrip('/')).stat().st_size
        manifest[url] = {'src': src, 'width': width, 'height': height,
                         'srcset': ', '.join(f'{u} {w}w' for u, w, h in variants),
                         'thumbnail': variants[0][0]}

(ROOT / 'assets/js/project-image-manifest.js').write_text(
    '// Generated by scripts/optimize-project-images.py.\nwindow.ArtilingProjectImages = ' +
    json.dumps(manifest, ensure_ascii=False, separators=(',', ':')) + ';\n', encoding='utf-8')
print(json.dumps({'images': len(paths), 'originalBytes': original_bytes, 'galleryBytes': gallery_bytes,
                  'reductionPercent': round((1-gallery_bytes/original_bytes)*100, 1)}))
